package com.covidtracking.CovidTracking;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1479, 837));
    driver.findElement(By.cssSelector(".active span")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(6) > .nav-link")).click();
    driver.findElement(By.id("country")).click();
    driver.findElement(By.id("country")).sendKeys("Portugal");
    driver.findElement(By.id("searchButton")).click();
    {
      WebElement element = driver.findElement(By.id("searchButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("country")).click();
    driver.findElement(By.id("country")).click();
    {
      WebElement element = driver.findElement(By.id("country"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("country")).sendKeys("azores");
    driver.findElement(By.cssSelector(".fa-search")).click();
    //assertThat(driver.switchTo().alert().getText(), is("This country doens\'t exist! Try another one"));
    driver.findElement(By.id("country")).click();
    driver.findElement(By.id("country")).click();
    {
      WebElement element = driver.findElement(By.id("country"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("content")).click();
  }
}
